### PR TITLE
Fix for translations

### PR DESCRIPTION
**Pull request by stefonarch**
Renamed correctly all files and updated  frontend/CMakeLists.txt
The latter could be fixed somehow I guess.

### CODE REVIEW

**Comment by stefonarch** [comment]
I see that this repo is not yet configured in LXQtBot @yan12125 
In weblate there are hebrew, portuguese  and japonese already translated.

**Comment by yan12125** [comment]
> I see that this repo is not yet configured in LXQtBot

Thanks for the reminder. Should be done now.

**Comment by stefonarch** [comment]
Something is strange, even after pushing again:
```
On branch master
Your branch is ahead of 'origin/master' by 4 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
```

Is there a webhook configured? I think not because I saw nothing and pulled manually.
Locked for now.

Edit: Here they came in https://github.com/lxqt/lxqt_wallet/pull/20
0 files changed.
Did a reset from the GUI.
Could well be the same  in other repos too, I did never merge those 0 files commits and closed the PRs.

**Comment by yan12125** [comment]
Dunno. I guess it is an edge case that Weblate cannot handle. If something goes wrong again, please tell me.

**Pull request merged**
