### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/lxqt-desktop/lxqt-wallet/) for LXQt Desktop/LXQt Wallet.

### CODE REVIEW

**Comment by yan12125** [comment]
@stefonarch there is a file translations/translations_it.ts - is it expected?

**Comment by stefonarch** [comment]
The language files were a big mess, I fixed all the names [here](https://github.com/lxqt/lxqt_wallet/commit/54ca8bc2f973bceec295a8d9d0e63bc781398751) but the template has still the old name translations.ts.
But filemaskis ok, and new files too. So I don't know exactly where this it.ts comes from. But there is also pt_PT.ts as gift.

Not sure what's the best approach now. Maybe just merging and remove the wrong file it.ts with a PR. There is also one needed for inserting the new translations in the code (see my merged commit).

Before merging I'll remove the pt_PT  file in weblate GUI. FYI I removed pt_PT and some de_XY files from weblate to prevent issues.

**Comment by stefonarch** [comment]
EDIT: as  pt_PT  is removed from weblate the empty *pt_PT it is not shown in the GUI, only the error.

**Comment by stefonarch** [comment]
Hopefully no rebase failure now.

**Pull request merged**
